export enum NotificationTypeEnum {
  ROLE_APPROVED = 'role_approved',
  ROLE_REJECTED = 'role_rejected',
  MEETING_REQUEST = 'meeting_request',
  MEETING_ACCEPTED = 'meeting_accepted',
  MEETING_REJECTED = 'meeting_rejected',
  CONNECTION_REQUEST = 'connection_request',
  CONNECTION_ACCEPTED = 'connection_accepted',
  CONNECTION_REJECTED = 'connection_rejected',
  CAREER_INTERVIEW_ASSIGNED = 'career_interview_assigned',
  CAREER_INTERVIEW_RESCHEDULED = 'career_interview_rescheduled',
  CAREER_INTERVIEW_CANCELLED = 'career_interview_cancelled',
  CAREER_SLOT_APPROVED = 'career_slot_approved',
  CAREER_SLOT_DECLINED = 'career_slot_declined',
}
